% Create a class for Suppliers...
classdef Supplier
    % Defining properties for each Supplier...
    properties
        DownStream_Info      % A vector of FORECASTS from Raymond's code...
        UpStream_Info        % Capability? Current Plan? Shipments?...
        ParentLabel          % Label of Parent Supplier...
        ChildrenLabels       % Label of Children Suppliers...
        NumberOfChildren     % Number of children suppliers...
        InputInventory       % Inventory for Input Parts...
        OutputInventory      % Inventory for Production...
    end
    % Methods
    methods
        function obj = Supplier(DownStream_Info, UpStream_Info, ParentLabel, ChildrenLabels)
            obj.DownStream_Info = DownStream_Info;
            obj.UpStream_Info = UpStream_Info;
            obj.ParentLabel = ParentLabel;
            obj.ChildrenLabels = ChildrenLabels;
            obj.NumberOfChildren = length(ChildrenLabels);
            obj.InputInventory = zeros(1, obj.NumberOfChildren);
            obj.OutputInventory = 0;
        end
    end
end